import { Express } from "express";
import { createAuthModule } from "./modules/auth/auth.module";
import { createClassesModule } from "./modules/classes/classes.module";
import { createItemsModule } from "./modules/items/items.module";
import { createInventoryModule } from "./modules/inventory/inventory.module";
import { createMapsModule } from "./modules/maps/maps.module";
import { createQuestsModule } from "./modules/quests/quests.module";
import { createGuildModule } from "./modules/guild/guild.module";
import { createMarketModule } from "./modules/market/market.module";
import { createNpcModule } from "./modules/npc/npc.module";
import { createEventsModule } from "./modules/events/events.module";
import { createAdminModule } from "./modules/admin/admin.module";
import { createSeasonsAdminModule } from "./modules/admin/seasonsAdmin";
import { createCharacterModule } from "./modules/characters/character.module";
import { createRedeemModule } from "./modules/redeem/redeem.module";
import { createContentModule } from "./modules/content/content.module";
import { createSeasonsModule } from "./modules/seasons/seasons.module";
import { createShopModule } from "./modules/shop/shop.module";
import { createRaidModule } from "./modules/raid/raid.module";
import { createLeaderboardModule } from "./modules/leaderboard/leaderboard.module";
import { createCraftModule } from "./modules/craft/craft.module";
import { createGachaModule } from "./modules/gacha/gacha.module";
import { createPvpModule } from "./modules/pvp/pvp.module";
import { PvpService } from "./modules/pvp/pvp.service";

export function registerModules(app: Express): void {
  createAuthModule(app);
  createCharacterModule(app);
  createClassesModule(app);
  createItemsModule(app);
  createInventoryModule(app);
  createMapsModule(app);
  createQuestsModule(app);
  createGuildModule(app);
  createMarketModule(app);
  createNpcModule(app);
  createEventsModule(app);
  createRedeemModule(app);
  createContentModule(app);
  createSeasonsModule(app);
  createShopModule(app);
  createRaidModule(app);
  createLeaderboardModule(app);
  createCraftModule(app);
  createGachaModule(app);
  createAdminModule(app);
  createSeasonsAdminModule(app);
  createPvpModule(app, app.get("pvpService") as PvpService);
}
